"""Demo `sram`: una SRAM de 16 palabras de 8 bits de SKY130 (OpenRAM) con 7
commits, una rama y un merge. Muestra jerarquía: un cambio en una sub-celda
aparece en cada una de sus instancias.

Fuente: `examples/GDS/sram_16x8_sky130.gds` (OpenRAM, BSD-3-Clause; celdas de
SkyWater, Apache-2.0).

    python3 tools/demos/sram.py <salida.bundle>
"""
import os
import sys

import klayout.db as db

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from common import Repo  # noqa: E402

HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.join(HERE, "..", "..", "examples", "GDS", "sram_16x8_sky130.gds")
GDS = "sram_16x8_sky130.gds"
BITCELL_MET2 = "sky130_fd_bd_sram__sram_sp_cell_met2"
DFF = "sky130_fd_bd_sram__openram_dff"
PMOS = "sram_16x8_sky130_pmos_m1_w1_120_sli_dli_da_p"
BANK = "sram_16x8_sky130_bank"

README = """# 16×8 SRAM (SKY130, OpenRAM) · Riku demo

A 16-word × 8-bit SRAM macro generated by OpenRAM for SKY130: 157 cells, the
bitcell placed 153 times. Seven commits with a branch (`fill`) and a merge,
to see how Riku shows changes deep in a hierarchy.

Things to try:

```bash
riku log --graph                          # the history
riku show HEAD~3                          # a bitcell change, seen in its 153 instances
riku show HEAD~2                          # a renamed cell (same geometry)
riku show fill                            # metal4 fill: hundreds of polygons, XOR by quadrants
riku diff v0.1 v1.0 -f visual             # the whole macro in the viewer
riku open                                 # H opens the history; the Cells list filters "only changed"
```

Source: `sram_16x8_sky130` generated with [OpenRAM](https://github.com/VLSIDA/OpenRAM)
(BSD-3-Clause) using the SkyWater SRAM cells (Apache-2.0); see `LICENSE`. The
changes are Riku's, to show its diffs.
"""

LICENSE = """This demo contains a layout generated by OpenRAM for the SkyWater SKY130 PDK.

OpenRAM: BSD 3-Clause License, Copyright (c) 2016-2024 Regents of the
University of California and The Board of Regents for the Oklahoma
Agricultural and Mechanical College. https://github.com/VLSIDA/OpenRAM

SRAM cells (sky130_fd_bd_sram): Apache License 2.0, Copyright 2020 SkyWater
PDK Authors. https://github.com/google/skywater-pdk-libs-sky130_fd_bd_sram

The modifications in this repository's history were made by the Riku
project to demonstrate its diffs.
"""


def edit_gds(repo, fn):
    ly = db.Layout()
    ly.read(repo.file(GDS))
    fn(ly)
    ly.write(repo.file(GDS))


def um(ly, v):
    return round(v / ly.dbu)


def wider_bitline(ly):
    """Las pistas de metal2 de la celda de bit, 10 nm más anchas de cada lado."""
    cell = ly.cell(BITCELL_MET2)
    m2 = ly.layer(69, 20)
    region = db.Region(cell.shapes(m2)).sized(um(ly, 0.01), 0)
    cell.shapes(m2).clear()
    cell.shapes(m2).insert(region)


def rename_pmos(ly):
    ly.rename_cell(ly.cell(PMOS).cell_index(), "sram_16x8_sky130_pmos_w1p12_da")


def wider_dff_rails(ly):
    """Los rieles de alimentación del flip-flop (`li` de lado a lado), 30 nm
    más anchos hacia afuera."""
    cell = ly.cell(DFF)
    m1 = ly.layer(67, 20)
    box = cell.bbox()
    for s in list(cell.shapes(m1).each()):
        b = s.bbox()
        if b.width() < 0.9 * box.width():
            continue
        grow = um(ly, 0.03)
        top = b.center().y > box.center().y
        new = db.Box(b.left, b.bottom, b.right, b.top + grow) if top else db.Box(b.left, b.bottom - grow, b.right, b.top)
        cell.shapes(m1).insert(new)


def fill(ly, skip_array):
    """Relleno de metal4: cuadrados de 1,6 µm cada 4 µm, lejos del metal4 que
    ya hay (y, con `skip_array`, fuera del arreglo de bits)."""
    top = ly.top_cell()
    m4 = ly.layer(71, 20)
    # Lejos del metal4 y de las vías de metal3 y metal4: el relleno flota.
    keep_out = db.Region()
    for l in [(71, 20), (70, 44), (71, 44)]:
        keep_out += db.Region(top.begin_shapes_rec(ly.layer(*l)))
    keep_out = keep_out.sized(um(ly, 1.0))
    if skip_array:
        bank = [i for i in top.each_inst() if ly.cell(i.cell_index).name == BANK][0]
        keep_out += db.Region(bank.bbox())
    squares = db.Region()
    b = top.bbox()
    step, size = um(ly, 4.0), um(ly, 1.6)
    y = b.bottom + step // 2
    while y + size < b.top:
        x = b.left + step // 2
        while x + size < b.right:
            squares.insert(db.Box(x, y, x + size, y + size))
            x += step
        y += step
    squares = squares.select_not_interacting(keep_out)
    top.shapes(m4).insert(squares)


def unfill_array(ly):
    """Saca los cuadrados de relleno que caen sobre el banco (solo ellos: el
    resto del metal4 del nivel superior es ruteo de alimentación)."""
    top = ly.top_cell()
    m4 = ly.layer(71, 20)
    bank = [i for i in top.each_inst() if ly.cell(i.cell_index).name == BANK][0].bbox()
    side = um(ly, 1.6)
    for s in list(top.shapes(m4).each()):
        b = s.bbox()
        if b.width() == side and b.height() == side and b.overlaps(bank):
            top.shapes(m4).erase(s)


def main():
    out = sys.argv[1] if len(sys.argv) > 1 else "examples/demos/sram.bundle"
    repo = Repo("/tmp/riku-demo-sram")
    print("sram")
    repo.write("README.md", README)
    repo.write("LICENSE", LICENSE)
    repo.copy(SRC, GDS)
    repo.commit("Initial SRAM macro (OpenRAM, 16x8)", tag="v0.1")
    edit_gds(repo, wider_bitline)
    repo.commit("Bitcell: 20 nm wider bitline metal2")
    edit_gds(repo, rename_pmos)
    repo.commit("Rename the precharge PMOS cell")

    repo.branch("fill")
    edit_gds(repo, lambda ly: fill(ly, skip_array=False))
    repo.commit("Add metal4 fill")
    edit_gds(repo, unfill_array)
    repo.commit("Keep the metal4 fill off the bitcell array")

    repo.checkout("main")
    edit_gds(repo, wider_dff_rails)
    repo.commit("Flip-flop: wider power rails")

    def resolve():
        repo.git("checkout", "--ours", GDS)
        edit_gds(repo, lambda ly: fill(ly, skip_array=True))
    repo.merge("fill", "Merge branch 'fill'", resolve)
    repo.git("tag", "v1.0")
    repo.bundle(os.path.abspath(out))


if __name__ == "__main__":
    main()
